### ISSUE TITLE
Goto def not working for std lib functions

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/plugin-vscode#303]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by grainier** [comment]
I'm also getting the same issue when try to `goto def fromBytes` of `string:fromBytes(message.content)` Please find the output;

```
[Error - 2:08:46 PM] Operation 'text/definition' failed! {uri: '/Users/grainier/Github/ballerina-event-sourcing/main.bal', [15:49], error: 'No value present'}
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:382)
	at org.ballerinalang.langserver.util.definition.DefinitionUtil.getLocation(DefinitionUtil.java:82)
	at org.ballerinalang.langserver.util.definition.DefinitionUtil.getDefinition(DefinitionUtil.java:61)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$definition$3(BallerinaTextDocumentService.java:257)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
